- type: technology
  id: RiotControl
  name: next-research-technology-riot-control
  icon:
    sprite: Objects/Weapons/Guns/Battery/particle_decelerator.rsi
    state: base
  discipline: RiotControl
  tier: 1
  cost: 5500
  recipeUnlocks:
   - WeaponDisabler
   - HoloprojectorField

- type: technology
  id: RiotControlAdvanced
  name: next-research-technology-riot-control-advanced
  icon:
    sprite: Objects/Weapons/Melee/truncheon.rsi
    state: icon
  discipline: RiotControl
  tier: 1
  cost: 8000
  recipeUnlocks:
   - Truncheon
   - TelescopicShield
   - HoloprojectorSecurity
   - WeaponDisablerSMG
   - PortableRecharger
  technologyPrerequisites:
  - RiotControl

- type: technology
  id: WarCrimes
  name: next-research-technology-war-crimes
  icon:
    sprite: Clothing/Back/Backpacks/electropack.rsi
    state: icon
  discipline: WarCrimes
  tier: 1
  cost: 7000
  recipeUnlocks:
   - ClothingBackpackElectropack
   - WeaponParticleDecelerator
  technologyPrerequisites:
  - RiotControlAdvanced
